site_name: Sohil Sisodiya
nav:
  - Home: index.md
  - About: about.md
  - Projects: projects/index.md
  - Blog: 
    - blog/index.md


# add repo
repo_url: https://github.com/sohil-sisodiya/portfolio
repo_name: sohil-sisodiya/portfolio

theme:
  name: material
  # custom_dir: overrides
  palette:
 
    # light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/light-flood-up
        name: Switch to dark mode

        # dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/light-flood-down
        name: Switch to light mode
  

  # logo
  icon:
    logo: simple/numba
    repo: octicons/git-branch-24
  

  #favicon: favicon.ico
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - toc.follow
    - search.suggest
    - content.code.copy

extra:
  generator: false
  social:
    
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/sohilverse
  
    - icon: fontawesome/brands/github
      link: https://github.com/sohil-sisodiya

    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/sohil-sisodiya
    
    - icon: fontawesome/solid/paper-plane
      link: mailto:<sohilsisodiya12@gmil.com>


# extra_css:
#   - assets/stylesheets/extra.css

# extra_javascript:
#   - javascripts/extra.js
  

plugins:
  - search
  - blog
  - tags


# code block 
markdown_extensions:
  - toc:
      permalink: ⚓︎
      toc_depth: 2

  - pymdownx.extra
  - pymdownx.betterem
  - pymdownx.highlight:
      anchor_linenums: true
      # auto_title: true
      # linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.mark

  # this is for tabs - it allows you to create tabbed content.
  - pymdownx.tabbed:
      alternate_style: true

  # this is for admonition - it is used to create callouts like note, warning, tip, etc.
  - admonition

  # this is for code block attributes - it allows you to add attributes to code blocks
  - attr_list



copyright: "© 2025 sohilsisodiya. All rights reserved."
