site_name: Sohil Sisodiya
nav:
  - Home: index.md
  - About: about.md
  - Projects: projects/index.md
    # - Customer Churn Prediction: projects/project1.md
    # - Project two: projects/project2.md
  - Codebook: codebook/index.md
  - blog:
    - blog/index.md


# add repo
repo_url: https://github.com/sohil-sisodiya/portfolio
repo_name: sohil-sisodiya/portfolio

theme:
  name: material
  # custom_dir: overrides
  palette:
 
    # light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/light-flood-up
        name: Switch to dark mode

        # dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/light-flood-down
        name: Switch to light mode
  

  # logo
  icon:
    logo: simple/numba
    repo: octicons/git-branch-24
  

  #favicon: favicon.ico
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - toc.follow
    - search.suggest
    - content.code.copy
    - blog

extra:
  generator: false
  social:
    
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/sohilverse
  
    - icon: fontawesome/brands/github
      link: https://github.com/sohil-sisodiya

    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/sohil-sisodiya
    
    - icon: fontawesome/solid/paper-plane
      link: mailto:<sohilsisodiya12@gmil.com>


# extra_css:
#   - assets/stylesheets/extra.css

# extra_javascript:
#   - javascripts/extra.js
  

plugins:
  - search
  - blog
  - tags


# code block 
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.extra
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.mark


copyright: "© 2025 sohilsisodiya. All rights reserved."
